<?php

namespace FondOfSpryker\Zed\CategoryStoreDataImport\Business;

use Spryker\Zed\CategoryDataImport\Business\CategoryDataImportFacadeInterface as SprykerCategoryDataImportFacadeInterface;

interface CategoryStoreDataImportFacadeInterface extends SprykerCategoryDataImportFacadeInterface
{
}
